# Generated by Django 4.2.2 on 2023-07-18 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allproducts', '0002_alter_product_options'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='product_favorite',
            field=models.ManyToManyField(to='allproducts.product'),
        ),
    ]
