# Generated by Django 4.2.2 on 2023-10-31 20:04

import creditcards.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderdetails_options_alter_order_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 31, 20, 4, 17, 786613, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='card_number',
            field=creditcards.models.CardNumberField(max_length=25),
        ),
    ]
